### ISSUE TITLE
Bug during submission of a workflow if go back is clicked

### ISSUE THREAD

**Issue by MicheleCD** [rosalindfranklininstitute/empiar-spw#11]
I added a section to a workflow, clicked submit on the section and then on the workflow and saw a summary page as expected.

I clicked the "Go Back" button and did nothing, but clicked submit on the workflow again. The summary page now erroneously showed two entries for the section that I had previously saved.

When I clicked "Go Back" again, two identical sections are now erroneously present in my protocol. 

Related, when I started a new workflow to do some testing around this bug, clikc save on a section and the workflow, the summary shows sections from the first workflow, but no sections from the second workflow. 

There seem to be some issues with saving a workflow and also accessing multiple workflows.

**Comment by nickcrawford1** [comment]
Awaiting update from EBI containing fix for this issue
