### ISSUE TITLE
Chemical Fixation Module - Neg Values shouldn't be allowed

### ISSUE THREAD

**Issue by MicheleCD** [rosalindfranklininstitute/empiar-spw#16]
In the Chemical Fixation Module, negative values for pH, Duration and repeats shouldn't be allowed.

**Comment by Demeter9** [comment]
This issue have been fixed and is ready to be reviewed in localhost:3002

**Comment by MicheleCD** [comment]
reviewed - looks good!

**Comment by Demeter9** [comment]
closed as part of merge request #22
