### ISSUE TITLE
Chemical Fixation - Instrument Wattage field is different here...

### ISSUE THREAD

**Issue by MicheleCD** [rosalindfranklininstitute/empiar-spw#18]
The Instrument Wattage field on the High Pressure Freezing module has a set of arrows off to the right to increase/decrease numbers. 

The Instrument Wattage field on the Chemical Fixation page doesn't have this (and there are two of these fields for some reason).

We should be consistent - I think I prefer the option with the arrows as it indicates that a number goes there. Please make this change here. 

Can you also find any additional instances of Instrument Wattage and make the change there if needed?

And could you also check the code for the double Instrument Wattage fields and see if there's any indication as to what the repeat field is actually meant to be? If there's no indication of something else, then please remove the second one.

**Comment by Demeter9** [comment]
The reported problems were identical in 'Chemical Fixation', 'Rinsing' and 'Incubation'. No hints in the code why the fields have been duplicated in these particular cards. The issues have been fixed and are deployed in localhost:3002 and can be reviewed

**Comment by MicheleCD** [comment]
reviewed all instrument wattage fields mentioned above. all look good.

**Comment by Demeter9** [comment]
closed as part of merge request #22
