### ISSUE TITLE
Plunge Freezing: Add new fields

### ISSUE THREAD

**Issue by MicheleCD** [rosalindfranklininstitute/empiar-spw#24]
Add a new section called Blotting
In that section add the following fields:
* Blot Type

This should be a drop down field including the following options:
Single sided - back
Single sided - front
Double sided

* Blot Force

This should be an integer field that allows both positive and negative values

* Blot Duration (in seconds)

This should be a real number field that only allows positive values.

**Comment by Demeter9** [comment]
@nickcrawford1 Not sure if adding a new sections is fine or need to do more work on backend for this to work. I am pushing this in any case, so you can decide if you merge or not
