### ISSUE TITLE
Dehydration: Count field in reagent concentration should be removed

### ISSUE THREAD

**Issue by MicheleCD** [rosalindfranklininstitute/empiar-spw#33]
The count field in the Reagent Concentration dropdown should be removed. 

For most protocols the count will be 1 with only a few exceptions, so it seems silly to add extra work for the user to set this to 1 most of the time and to something else infrequently when just having the entry in the first place functions to indicate a single entry.  For those times when the same thing is done 2x, the user can just input the second time as a separate entry.

**Comment by MicheleCD** [comment]
I had a second thought about this - should the count section be updating to indicate the order? I noticed that you could add as many instances of this info as needed and that they could be re-ordered, but the count didn't update... Not sure if this is a bug or if it's an unnecessary field. 

Worth a convo with Sriram I think before we do anything.

**Comment by Demeter9** [comment]
@MicheleCD Could you please explain what it means to update the count to indicate order? Don't understand whats the purpose of this field

**Comment by Demeter9** [comment]
@MicheleCD confirmed we can delerte this field

**Comment by Demeter9** [comment]
ready for review and merge on pull request #48
