### ISSUE TITLE
Modifications to the Review step - Initial Feedback

### ISSUE THREAD

**Issue by MicheleCD** [rosalindfranklininstitute/empiar-spw#77]
The units for duration and concentration do not show up in the review step even though they've been entered throughout the protocol. Please include the units that have been chosen for all durations and concentrations.
![image](https://github.com/user-attachments/assets/c72ce5be-9ee0-4017-b950-b0095cca761b)

**Comment by Demeter9** [comment]
Will make this apply to 'chemical fixation' only and make new tickets for the other cards. That is because other cards have more problems even if i fix the concentrations issue and their review card doesn't show up anyway. This way there will be a ticket per card

**Comment by Demeter9** [comment]
Fixing instrument that was not working for 'Chemical fixation' as well
