### ISSUE TITLE
Negative values shouldn't be possible

### ISSUE THREAD

**Issue by MicheleCD** [rosalindfranklininstitute/empiar-spw#8]
In the High Pressure Freezing section of Build a Workflow

Negative numbers should not be possible for Pressure, Duration or Bore Diameter.

**Comment by Demeter9** [comment]
This issue have been fixed and is ready to be reviewed in localhost/3002

**Comment by MicheleCD** [comment]
reviewed - looks good.

**Comment by Demeter9** [comment]
closed as part of merge request #22
